package cli

import (
	"fmt"
	"strconv"

	"cria/internal/format"
)

// wiredLimitPlist is the launchd job `cria wired-limit` generates: it re-applies
// the Metal wired-memory limit at every boot, because iogpu.wired_limit_mb
// resets to the macOS default on reboot and big models need the headroom. cria
// generates the file and the user installs it — cria itself writes nothing and
// touches no system state (docs/cria.md, principle 1; docs/specs/CLI.md).
const wiredLimitPlist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  Re-applies the Metal wired-memory limit at every boot: iogpu.wired_limit_mb
  resets to the macOS default on reboot, and big models need the headroom.
  The value is per-machine; this file was generated by %s.
  Uninstall:
    sudo launchctl bootout system/local.iogpu-wired-limit
    sudo rm /Library/LaunchDaemons/local.iogpu-wired-limit.plist
-->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>local.iogpu-wired-limit</string>
  <key>ProgramArguments</key>
  <array>
    <string>/usr/sbin/sysctl</string>
    <string>iogpu.wired_limit_mb=%d</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
`

// wiredLimitHelp is what lands on stderr beside the plist: every sudo step is
// the user's to run — cria never installs anything.
const wiredLimitHelp = `This machine has %s of memory; a limit of %d MB (%s) leaves %s for macOS.

Save the plist (it is on stdout):
  cria wired-limit %d > iogpu-wired-limit.plist

Install it (root-owned, or launchd refuses to load it):
  sudo cp iogpu-wired-limit.plist /Library/LaunchDaemons/local.iogpu-wired-limit.plist
  sudo chown root:wheel /Library/LaunchDaemons/local.iogpu-wired-limit.plist
  sudo chmod 644 /Library/LaunchDaemons/local.iogpu-wired-limit.plist
  sudo launchctl bootstrap system /Library/LaunchDaemons/local.iogpu-wired-limit.plist

The bootstrap also applies it immediately; verify with:
  sysctl iogpu.wired_limit_mb

Uninstall:
  sudo launchctl bootout system/local.iogpu-wired-limit
  sudo rm /Library/LaunchDaemons/local.iogpu-wired-limit.plist
`

// wiredLimit is `cria wired-limit <MB>`: the plist to stdout — so a redirect
// yields a clean file wherever the user wants it — and the instructions to
// stderr, mirroring `cria docs`: cria as generator, the shell as writer.
func (a *app) wiredLimit(args []string) int {
	if len(args) != 1 {
		return a.usage("wired-limit: one megabyte value; usage: cria wired-limit <MB>")
	}
	limit, err := strconv.Atoi(args[0])
	if err != nil {
		return a.usage("wired-limit: %q is not a whole number of megabytes; usage: cria wired-limit <MB>", args[0])
	}
	if limit <= 0 {
		return a.fail("wired-limit: %d MB pins no memory; name the megabytes the GPU may wire", limit)
	}

	ramMB, err := a.memoryMB()
	if err != nil {
		return a.fail("wired-limit: %v", err)
	}
	if limit >= ramMB {
		return a.fail("wired-limit: %d MB is not less than this machine's %d MB of memory; the limit must leave macOS room to run", limit, ramMB)
	}

	a.printf(wiredLimitPlist, "`cria wired-limit "+args[0]+"`", limit)
	fmt.Fprintf(a.err, wiredLimitHelp,
		format.Bytes(int64(ramMB)<<20), limit, format.Bytes(int64(limit)<<20),
		format.Bytes(int64(ramMB-limit)<<20), limit)
	return exitOK
}
